version: '3'

networks:
  victor_gpt_network:
    name: victor_gpt_network
    #external: true

services:
  proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - 0.0.0.0:8080:80
    depends_on:
      - backend
      - frontend
    networks:
      - victor_gpt_network

  backend:
    container_name: backend
    #profiles: ["production"]
    build:
      context: ../backend/
      target: production
    ports: 
      - 0.0.0.0:2000:2000
    tty: true 
    command: "go run ."
    volumes:
    - ../backend:/app:z
    networks:
      - victor_gpt_network

  frontend:
    container_name: frontend
    #profiles: ["production"]
    build:
      context: ../frontend/
      target: production
    ports: 
      - 0.0.0.0:9000:3000
    tty: true 
    command: "npm start"
    volumes:
    - ../frontend/client/:/app/:z
    networks:
      - victor_gpt_network

#  chat_gpt_service:
#    build: 
#      context: ../ChatGPT-API-server
#    ports:
#      - 0.0.0.0:2001:2001
#    command: ["ChatGPT-API-server", "8080", "clave_administradora", "-listen", "0.0.0.0"]
#    volumes:
#      - ./.env:/app/.env:ro
#    tty: true 
