version: '3.4'


networks:
  my-network:
    driver: bridge

services:

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - 0.0.0.0:8080:80
    depends_on:
      - backend
      - frontend
    networks:
      default:
        aliases:
          - proxy-network

  backend:
    build:
      context: ../backend/
      target: develop
      #target: production
    ports: 
      - 0.0.0.0:2000:2000
    tty: true 
    #command: "go run ."
    volumes:
    - ../backend:/app:z
    - ./.env:/app/.env:z
    
  frontend:
    build:
      context: ../frontend/
      target: develop
      #target: production
    ports: 
      - 0.0.0.0:9000:3000
    tty: true 
    #command: "npm start"
    volumes:
    - ../frontend/client/src:/app/src:z
    - ./.env:/app/.env:z

#  chat_gpt_service:
#    build: 
#      context: ../ChatGPT-API-server
#    ports:
#      - 0.0.0.0:2001:2001
#    command: ["ChatGPT-API-server", "8080", "clave_administradora", "-listen", "0.0.0.0"]
#    volumes:
#      - ./.env:/app/.env:ro
#    tty: true 
